### ISSUE TITLE
winKex opens Windows Manager (xfwm4) without working taskbar and windows borders/tiles (WSL)

### ISSUE THREAD

**Issue by CosmicTiger** [aioont/kex#4]
### Windows Version

Microsoft Windows [10.0.22621.0]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.90.1

### Distro Version

Kali Linux 2023.2

### Repro Steps

1. Open respective kali-linux distro (either exported WSL image or current Microsoft Store generated image)
2. Execute `kex -w` or `kex -esm` or either client options available for winKex once installed
3. Opens Windows of the Kali Linux desktop from WSL

### Expected Behavior

Obtain proper operation as described in documentation
![image](https://github.com/microsoft/WSL/assets/30613501/e6e4c7c5-cf68-4926-8bf3-8a1071e46286)

![image](https://github.com/microsoft/WSL/assets/30613501/2c065a71-c873-49c9-b2bd-76549626586b)

### Actual Behavior

xfce Windows manager not working accordingly  by not showing either taskbar or windows tiles/borders even after reinstall in my used distro and in a new one as demonstrated below.
![image](https://github.com/microsoft/WSL/assets/30613501/9b572dde-414c-4243-8ca9-a93c6f9c4c94)

![image](https://github.com/microsoft/WSL/assets/30613501/6e0fd18f-346c-4836-ba68-fd13669df294)

![image](https://github.com/microsoft/WSL/assets/30613501/d40d522d-881e-450d-b18c-039337168e6e)

### Diagnostic Logs

Not added because I'm not sure what log files could be of value for troubleshooting this issue.

**Comment by aioont** [comment]
Actually, I'm not using WSL; instead, I previously used Kali Linux in mobile phone using kali nethunter. I apologize for any confusion caused. Unfortunately, I'm not familiar with the specific issue you're currently facing. However, I appreciate your effort in providing detailed documentation of the error you're encountering.

Could you try below steps :
`sudo apt reinstall xfce4`
Reset xfce settings: Resetting the xfce settings to their default values may help resolve the issue. You can do this by deleting the ~/.config/xfce4 directory. Run the following command to delete it:
`rm -rf ~/.config/xfce4`
Reset display settings: Resetting the display settings to their default values might also help. You can do this by deleting the ~/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml file. Run the following command to delete it:
`rm ~/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml`

After trying these steps, restart your Kali Linux session and see if the xfce Windows manager functions correctly. If the issue persists, you may need to seek further assistance from the Kali Linux community or support channels, as it could be a specific issue related to the WSL 2 environment or your system configuration.

Source: ChatGPT

**Comment by CosmicTiger** [comment]
OMG @aioont YOU ARE THE GOAT. Actually helps me out. If happens another time I just will redo this. THANK YOU SO MUCH FRIEND. 
![image](https://github.com/aioont/kex/assets/30613501/946037ef-92e3-4f0a-860e-08c3b464d9d5)

**Comment by CosmicTiger** [comment]
Update: The problem still persists and I could still do your step by step process to solve it but, you think that there's a way to actually solve this issue permanently?

**Comment by aioont** [comment]
I'm not entirely sure about the specific problem you're facing. However, executing the commands and making the setup files read-only could potentially help. If you're experiencing this issue after every boot-up or shutdown, setting up a shell script to automatically execute the commands might be a solution worth considering.

1.Open a text editor and create a new file. You can name it something like "script.sh".
2.Add code 
> #!/bin/bash
sudo apt reinstall xfce4
rm -rf ~/.config/xfce4
rm ~/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml
chmod -R 444 ~/.config/xfce4 
     
3. Save the file and exit the text editor. and setup permission `chmod +x script.sh`
4. Execute by `./script.sh`

>    To execute the script on computer boot-up, you can add it to the system's startup applications. The steps to do this may vary depending on your Linux distribution and desktop environment. Here's a general approach:

    a. Open the startup applications preferences. You can usually find it in your system settings or by searching for "Startup Applications" in the application menu.

    b. Click on the "Add" or "New" button to create a new startup entry.

    c. Fill in the required fields, such as a name for the entry and the path to the script file (e.g., /path/to/script.sh).

    d. Save the changes and exit the preferences.


I hope you're familiar with log files. If you have a good understanding, feel free to analyze them on your own or share your insights within a community. Alternatively, you can utilize tools like ChatGPT or Bard to help you interpret the log data more effectively. Happy exploring!

Unfortunately, I don't have much knowledge about WSL and the specific problem you're facing. However, I recommend reaching out to the WSL Kali community as they might be able to provide more assistance. Have a great day!
